### ISSUE TITLE
Error when using import { ReactReader } from "react-reader";

### ISSUE THREAD

**Issue by muriloneo** [gerhardsletten/react-reader#45]
Fresh install.
`react-native init epub1`
`npm install react-reader --save`

change App.js with example:
```
<div style={{ position: "relative", height: "100%" }}>
        {" "}
        // * Container needs a height..
        <ReactReader
          url={"/alice.epub"}
          title={"Alice in wonderland"}
          location={"epubcfi(/6/2[cover]!/6)"}
          locationChanged={epubcifi => console.log(epubcifi)}
        />
      </div>

```
`react-native run-ios`

package.json
"dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-reader": "^0.17.11"
  },
  "devDependencies": {
    "@babel/core": "^7.6.0",
    "@babel/runtime": "^7.6.0",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.4.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6"
  },

error: bundling failed: Error: Unable to resolve module `stream` from `/Users/user/Sites/react-native/epub1/node_modules/jszip/lib/readable-stream-browser.js`: Module `stream` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/user/Sites/react-native/epub1/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:183:15)
    at ResolutionRequest.resolveDependency (/Users/user/Sites/react-native/epub1/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/Users/user/Sites/react-native/epub1/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/Users/user/Sites/react-native/epub1/node_modules/metro/src/lib/transformHelpers.js:264:42)
    at dependencies.map.result (/Users/user/Sites/react-native/epub1/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/user/Sites/react-native/epub1/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Users/user/Sites/react-native/epub1/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/user/Sites/react-native/epub1/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)

**Comment by gerhardsletten** [comment]
Hi, @muriloneo `react-reader` is not a react-native package, but meant to be used in regular react-apps (web-app)
